version: "3.9"

services:

  dev-mysql:
    image: mysql:latest
    restart: always
    networks:
      - dev-network
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dev-mysql:/var/lib/mysql
    ports:
      - 3306:3306

networks:
  dev-network:


volumes:
  dev-mysql:
